version: '3.9'

services:
  web:
    build:
      context: web
      args:
        crm_base_dir: ${CRM_BASE_DIR}
    container_name: crm_web
    hostname: web
    env_file:
      - .env
    volumes:
      - ./web:${CRM_BASE_DIR}/web
    networks:
      - default
    ports:
      - "3456:3456"
    depends_on:
      - api
    profiles:
      - dev

  api:
    build:
      context: api
      args:
        crm_base_dir: ${CRM_BASE_DIR}
    container_name: crm_api
    hostname: api
    env_file:
      - .env
    volumes:
      - ./api:${CRM_BASE_DIR}/api
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: crm_db
    hostname: db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  default:
    name: crm.skyd.ua
    driver: bridge