version: '3.9'

services:
  api:
    build:
      context: api
    container_name: crm_api
    hostname: api
    env_file:
      - .env
    volumes:
      - ./api:${CRM_API_DIR}
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: crm_db
    hostname: db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  default:
    name: crm.skyd.ua
    driver: bridge