### Login
POST {{base_url}}/login_check
Accept: application/json
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    const { token } = response.body;
    client.global.set('token', token)
%}

### Get User Summary
GET https://crm.nbfx.tech/users/admin
Accept: application/json
Authorization: Bearer {{token}}

### Get Users
GET {{base_url}}/users?page=1
Accept: application/json
Authorization: Bearer {{token}}

### Get Items
GET {{base_url}}/items?page=1
Accept: application/json
Authorization: Bearer {{token}}
